spring:
  application:
    name: 'employee'
  data:
    rest:
      base-path: '/api'
  datasource:
    username: perftest
    password: 123456
    url: 'jdbc:mysql://nckmvdsla12431:4006/employees?useSSL=false'
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      
